language: node_js
sudo: false
node_js:
- 6
- 4
script:
- npm run ci
- chmod 777 ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
- export TEST_GROUP=desktop-ci
- ./node_modules/@pearson-components/npm-scripts/shell_scripts/run_selenium_ci_tests.sh
after_success:
- npm run deploy-ci
deploy:
  provider: npm
  email: pearson-design-accelerator@pearson.com
  api_key:
    secure: AWrUX+KLKYJZoZE81jOI8a5HiNXuvYb2+aGN8AZ9gLIU99XiOjdnKpRmaPdCorwIeD7vi50qxyGRZ71JRMeXwcNtnPe93PeOeb19jAJ/2ImPQtu9bi74FdDoMHjf49KKqitZUOgHiSmAPnnkAar8PTqBC8M2FxIh+W5iiunzbsU8MQ7gy6LHFNwRonJ8AwCMW/0hK9vCsJTsp1wK8a41vEoMZ+xUBDBmXKjmmZTW5eokJNdzRW2IkvOsjZbyCeMUoIq6jbjRD1FRwUBh2r/DG0W47X9L73LIPWx1BF2Flt9g0bO4kctNUnbspRdm8EZ6cE59THq4Qr6Z0fMXf5bzUy/AReiAjIPb7DVyI8xtJwZptYUt1zqVKqZj8E8NWXrG+DPZ6qSBqRNBrYr/nw1+S+hRnOVb0cR6azXXAtBZY8AAYmt6L2f2MFhHH6es8viKWIceFlBDMC8yn9rUd4N2Ox5cavHwt8DChaCn4rebG2jdbF/6H0Eyf/uVJG7FmMlVy/0wQgxImUOLshTIYPYlV5qCmz0ARc/PnKv7FciGtl72eeGF0k4MmrrxkTK1ahuRHoaGx3MAW0idGgnn9460FNjKGIAYGbqrOKTnnGJr9KBp+xYahQ8q03wYhuY7HUwKhjmLm3bMSdiCsJdgA8eqaXUaj0V7ZrmC/Ot7004jkuM=
  skip_cleanup: true
  on:
    branch: v1
    tags: true
env:
  global:
  - secure: n08f23CJolhQG9KrUhD9CG5JU4RLQeLNNJgx7T4VbEBCMSugnRMdLya8QmpP3CFlSvt7s0maaRyRs6DWIdf+gIRa1lq8qmEGOGV3mGZj/eruVrUFuOyNuEaJo/bPhX2MvjejjPlqhFB5A5ZmGf04Zk5+zumtrXCZ9SfTNK7ub0zO8jvA0Yh+I2rRMjF/DlphsxNtkWPosOQ7jXt7Pdt0pMqKD6BN691YHywZ7l4Js/2UD3BdbeSEytdPeZVVnpem8EAEwGQHAQkJpHORNv6fe0yOTbXzX2Uv0Ulw54zbg2boH3gJaN+y4S9HmJKiuLgy0N4P80ecBX9AU6myRUVKrkfPNYgB2qo4sGipmdnxTuW+3P47aYHK96mQ6RakdZP0KcoNRPueWAd8SdeW3XXjfPr9dN8aywD0ppBgpLqC0IQe6teRYhTvm74fka1qIK1AkTQAsbCTHEexAnmFgzSxTGYbEF8D35WX6uYL34Z4raMjTR0wp6GklT47m1dLQWDgmlnxB/3pyu+v7MQgPBM+8fJH18ul/2IkAMnDtE4IhssvxV7rZO0I60HAWsLwH/tUumzGZbJeJhlgvDrzLqj9AbHeDKOTeGzJIRJLUlRX3nnhk917RCnoJn+kLmtW3mXU4EhlZ73EPvSI0xQh1EcRNGW3tUd6L2MF0W6gdHwF+rI=
notifications:
  hipchat: 8kYUBgqb3GTlHlMPzn94O8OX2YGOHOnUyG1qdoJF@2846476
